spring:
  application:
    name: discord-lite

  datasource:
    url: jdbc:postgresql://localhost:5432/discord_lite
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jwt:
    secret: ${JWT_SECRET_KEY}
  aws:
    iam-access-key: ${AWS_IAM_ACCESS_KEY}
    iam-secret-access-key: ${AWS_IAM_SECRET_ACCESS_KEY}
    aws-region: ${AWS_REGION}
    bucket-name: ${AWS_BUCKET_NAME}
server:
  port: 8080